### ISSUE TITLE
Max volume when unpausing music (sometimes occur)

### ISSUE THREAD

**Issue by Vaarelsauce** [Frank-Friemel/Shairport4w#20] opened 2022-07-08 08:59 UTC
EDIT: Iphone XR device.

For example, I set the shairport volume to 50%, and play a song on Spotify. When I pause the Spotify song to watch like a short YouTube video, and then unpause the Spotify song, the shairport volume would automatically be adjusted to 100% and blast my ears off. Is there any way to circumvent this auto-correction?

Or at least, I recommend implementing a feature where you can adjust shairport's "default" volume setting.

**Comment by REHCTELF-FLETCHER** [comment] 2022-08-31 08:22
Yea this also happens to me

**Comment by Frank-Friemel** [comment] 2022-09-28 09:00
This may be problem of iOS. Please record a log file -> it's available in the Options dialog. The log file appears in the same folder as Shairport.exe. You probably have to start Shairport "elevated" in case the exe is located in your program folder - otherwise the log file can not be created. Then reproduce the error. Afterwards, search the log file for the word "volume".

**Comment by Vaarelsauce** [comment] 2022-10-29 06:29
> This may be problem of iOS. Please record a log file -> it's available in the Options dialog. The log file will appear in the same folder as Shairport.exe. You probably have to start Shairport "elevated" in case the exe is located in your program folder - otherwise the log file can not be created. Then reproduce the error. Afterwards, search the log file for the word "volume".
> 
> Don't forget to disable the log option when you're done

Unfortunately, the problem still persists even after I:
1) Ran as adminstration / elevated status
2) Manually gave "Full Access" permission to every group/user
3) Created a log file, in the same Desktop folder as shairport4w.exe and searched for the word "volume". There doesn't seem to be anything out of the ordinary.

I have a pretty rough hypothesis of what's going on, though. I'm assuming that whenever my phone screen turns off, Shairport4w "disconnect" the connection with the phone passively, and kind of erasing all the temp stuff including volume. Whenever I play the music again, it wakes up the standby connection as if it was a cold start. 
So ultimately, the issue stems from.....my device "flushing the temp data" when I turn off the screen?

**Comment by Frank-Friemel** [comment] 2022-10-29 07:15
It‘s not clear to me which volume you mean. Is it the volume on your iPhone device? Or is it the volume on your PC? And please post the log file that you‘ve recorded

**Comment by Vaarelsauce** [comment] 2022-10-29 16:35
> It‘s not clear to me which volume you mean. Is it the volume on your iPhone device? Or is it the volume on your PC? And please post the log file that you‘ve recorded

The audio on the PC sounded as if the phone's sound level was adjusted to max, even though on the phone it remains at 10% sound level. Only when I adjust the phone's sound level up or down, will the audio on the PC gets "re-synced" to the accurate phone's sound level.

I've attached the debugging log file below.
[Shairport4wx64.log](https://github.com/Frank-Friemel/Shairport4w/files/9894151/Shairport4wx64.log)

**Comment by albino1** [comment] 2022-11-01 19:29
I've always had this, as long as I've used Shairport4w, as does the person who originally introduced me to Shairpor4w 3+ years ago since we've talked about it several times as the only real downside to using it. The audio jumps up in volume, however the volume slider hasn't changed on the phone.  If you move the slider even a tiny amount the volume returns to its currently set position.

Set the volume slider to something low like 10%, play something, pause it for an extended period, unpause it and the volume level is drastically increased.  Lightly touch the slider and the volume immediately drops back to 10%.

It's like the volume gets unset and you have to reset it.  I find this is much more obvious with podcasts than music as somebody who was previously talking quietly is now talking loudly.

I've had this with multiple iPhones across multiple versions of iOS, probably since at least iOS 13 with an iPhone XS Max.  I've always assumed it was a iPhone/iOS issue and there's nothing Shairport4w could do about it, but I would love to see a fix if possible.

This is currently on an iPhone 14 Pro Max running iOS 16.1 using Windows 10 Pro.

**Comment by Frank-Friemel** [comment] 2022-12-18 20:07
Should be fixed with version 1.0.9.6 https://github.com/Frank-Friemel/Shairport4w/releases/tag/1.0.9.6

**Closed by Frank-Friemel** 2022-12-18 20:07 UTC
Labels: bug

**Comment by albino1** [comment] 2022-12-19 00:15
It's early, and I've only just tested it with some play/pauses, and some switching podcasts, but it seems like it might be fixed!

I did notice that if I connect to Shairport, then switch to my phone audio, and then back to Shairport the volume drops, but that's probably not related, and honestly not a big deal.  The real problem was always pausing/playing and having volume jumps while still connected, and I haven't managed to trigger that.  I'll update after more testing in the next day or two.

Thank you so much!

**Comment by jamesvincent** [comment] 2024-06-06 09:14
I'm new to the party, but came here to see if anyone had mentioned the fact that reconnecting to SharePort4w after say a phone call etc, when reconnecting AirPlay, it's as though the hardcoded default "starting volume" is set to ~25%.

It would be nice if this "startup" volume could match OS volume, or be user selectable.

I have my PC set at the "right volume", for notifications etc - which is around 40% total output. But when I airplay, the music comes out at 25% of the 40% so its really quiet, and always requires me to turn it up....

Shouldn't really complain, ShairPort4w is the only app I've found that sits nicely in the Task Tray, and for that I am very happy/grateful.

**Comment by albino1** [comment] 2024-06-06 19:43
I agree, it would be nice if it just remembered the volume you used previously.
