### ISSUE TITLE
Can't change soundcard

### ISSUE THREAD

**Issue by NotAKidOnSteam** [Frank-Friemel/Shairport4w#5] opened 2019-02-06 00:03 UTC
Doesn't change sound output. Also can not change the sound output settings in the advanced sound settings section of the new windows 10 settings app.

**Comment by jvasileff** [comment] 2019-02-08 20:28
I have the same problem.

It _did_ work with an older version of Shaiport4w (and perhaps an older version of Windows 10?), but I wasn’t able to find download links for old versions, and I no longer have my copy.

**Comment by jvasileff** [comment] 2019-02-12 16:42
Looks like this is the same as #2, which was perhaps closed on accident by @Jokanok?

**Comment by viktor-morin** [comment] 2020-04-26 14:27
@jvasileff @NotAKidOnSteam 
Long time ago since you did your post, but I updated my version and I couldnt change output either.
So I went back to my old version where it works, version 1.0.8.8

You can download it here if you want:
https://www.dropbox.com/s/793cwdg6esd655g/SP4W_Setup.exe?dl=0

**Comment by JackPGreen** [comment] 2020-09-21 00:06
> @jvasileff @NotAKidOnSteam
> Long time ago since you did your post, but I updated my version and I couldnt change output either.
> So I went back to my old version where it works, version 1.0.8.8
> 
> You can download it here if you want:
> https://www.dropbox.com/s/793cwdg6esd655g/SP4W_Setup.exe?dl=0

Thanks - this downgrade resolves issue for me too.

**Comment by Frank-Friemel** [comment] 2022-12-16 19:01
Duplicate of #16

**Closed by Frank-Friemel** 2022-12-16 19:01 UTC
