### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by GertieMeneer** [Frank-Friemel/Shairport4w#31] opened 2023-01-25 20:00 UTC
When I pause the music on my phone and then go do something else on my pc, I am unable to unpause the music again and play through shairport. On my phone I get the "unable to connect to device" error and then I'm not able to find my pc in the airplay list again. I have to restart shairport to see it in the airplay list again.
iOS version: 16.3 on iPhone 11.
Windows version: 22H2 (Build 22621.1180)
Shairport version: dec 20, 2022

**Comment by Frank-Friemel** [comment] 2023-01-28 16:43
This seems to be a duplicate of bug #14

**Closed by Frank-Friemel** 2023-01-28 16:43 UTC
